### ISSUE TITLE
Error after init_epochs in training 

### ISSUE THREAD

**Issue by Yuzz1020** [researchmm/TTSR#36]
Hi, 

Thank you for your work! It is a great repo. 

I am trying to reproduce your results. After the init_epochs are finished, there is a bug with the following information. 

`Traceback (most recent call last): 
  File "main.py", line 45, in <module>
    t.train(current_epoch=epoch, is_init=False)
  File "/home2/zy42/TTSR/trainer.py", line 97, in train
    sr_lv1, sr_lv2, sr_lv3 = self.model(sr=sr) 
......
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last): 
......
  File "/home2/zy42/TTSR/model/TTSR.py", line 22, in forward
    self.LTE_copy.load_state_dict(self.LTE.state_dict())
RuntimeError: Error(s) in loading state_dict for LTE: 
        Missing key(s) in state_dict: "slice1.0.weight", "slice1.0.bias", "slice2.2.weight", "slice2.2.bias", "slice2.5.weight", "slice2.5.bias", "slice3.7.weight", "slice3.7.bias", "slice3.10.weight", "slice3.10.bias".`

It seems there are some missing keys when loading the LTE in the model/TTSR.py. I am training with the default train.sh setting using 3 GPUs. 

I can avoid this bug by setting strict=False when loading the parameters from LTE, but I am not sure if this will lead to performance degradation. 

Thank you for your time. 

Look forward to your reply!

**Comment by FuzhiYang** [comment]
You can print the state_dict of the model to check the difference between network and the pre-trained model. If there are differences, you can modify the name to match them.
