### ISSUE TITLE
KeyError: 'G_optimizer'

### ISSUE THREAD

**Issue by JusticeLin** [researchmm/TTSR#53]
When I was trainging,I met the problem as follow:
[2022-03-20 10:31:09,837] - [trainer.py file line:246] - INFO: start loading resume state... , path : ./experiments/train_cvt_wgan/training_state/TTSR.pt
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    t.load_all()
  File "/home/lzy30/Chaofen/TTGAN/TTGAN/trainer.py", line 249, in load_all
    self.resume_training(resume_state)
  File "/home/lzy30/Chaofen/TTGAN/TTGAN/trainer.py", line 255, in resume_training
    resume_optimizers = resume_state['G_optimizer']
KeyError: 'G_optimizer'

I have looked for the solution for several days,please help me solve the problem.Thank you very much!

**Comment by FuzhiYang** [comment]
It seems that you were trying another code repo? Could you describe your problems in more detail?
